### ISSUE TITLE
[Issue] Crash on install, report blames LaserIO for some reason

### ISSUE THREAD

**Issue by aaronhowser1** [nanite/Structure-Expansion#6] opened 2023-05-29 09:36 UTC
### Minecraft Version

1.19.2

### Modloader

43.2.8

### Mod version

structure-expansion-1902.1.3-build.7

### Repeatable?

- [X] Yes

### Link to log files

Crash report 1 https://gist.github.com/aaronhowser1/a61de9317ed4cd9a1b0e1bbd3a50e45b
Crash report 2 https://gist.github.com/aaronhowser1/4105d3f5e5617a3542f9241628ad9dea

latest.log https://gist.github.com/aaronhowser1/836c5176f1a4f6e73adb28912d436163
debug.log https://gist.github.com/aaronhowser1/9981f848751a9cde64a0ab4f8c2dda4e

### Description of the issue you are having

When I add it, it crashes. When I remove it, it doesn't.

### Information

- [X] I have provided as much information as possible

**Comment by Sunekaer** [comment] 2023-06-02 09:03
Duplicate of #5

**Closed by Sunekaer** 2023-06-02 09:03 UTC
